### ISSUE TITLE
Setup: mac unsupported?

### ISSUE THREAD

**Issue by 0todd0000** [Aravind-Sundararajan/MocoExtendProblem#5]
The setup instructions on the [main repo page](https://github.com/Aravind-Sundararajan/MocoExtendProblem) do not indicate that Windows is required, but scripts appear to expect Windows. For example, the [build.m](https://github.com/Aravind-Sundararajan/MocoExtendProblem/blob/main/build.m) script yields warnings like this on `macos`:

```
Warning: Name is nonexistent or not a directory: /Users/USERNAME/MocoExtendProblem/\opensim 4.5\bin 
```
which appears to mix macos and Windows-style paths

Is macos supported?  If not, no problem, please just state this in the Setup instructions and I'll switch over to Windows.

**Comment by Aravind-Sundararajan** [comment]
I had forgotten that SimTK allows you to download the pkg to install on macos. I did not develop with macos or linux distros in mind; however, msbuild through dotnet mono and cmake should be available to install, so technically, it should work if I change the paths, but I only have Matlab on Windows. Can you confirm that you have the required dependencies on macos: 

- Matlab

- cmake

- msbuild

- any OpenSim version 4.2-4.5

When installed on mac, where are opensim headers installed? We can also ignore all this and say it only works on Windows.

**Comment by 0todd0000** [comment]
> Can you confirm that you have the required dependencies on macos

Yes, I do indeed have the required software.

<br>
<br>

> When installed on mac, where are opensim headers installed? 

There are several header locations, but I think the main root in the default installation is:
```
/Applications/OpenSim 4.4/sdk
```
This is an alias for a folder inside the .app:
```
/Applications/OpenSim 4.4/OpenSim 4.4.app/Contents/Resources/opensim/sdk
```


<br>
<br>

> We can also ignore all this and say it only works on Windows.

I think this is a good idea. It may be best to limit support to Windows for purposes of review, as I don't think the supported platform(s) affect review outcome. So I'll shift over to Windows and retry setup. Please just indicate in the setup instructions that only Windows is explicitly supported at this stage.

**Comment by Aravind-Sundararajan** [comment]
> > Can you confirm that you have the required dependencies on macos
> 
> Yes, I do indeed have the required software.
> 
> 
> > When installed on mac, where are opensim headers installed?
> 
> There are several header locations, but I think the main root in the default installation is:
> 
> ```
> /Applications/OpenSim 4.4/sdk
> ```
> 
> This is an alias for a folder inside the .app:
> 
> ```
> /Applications/OpenSim 4.4/OpenSim 4.4.app/Contents/Resources/opensim/sdk
> ```
> 
> 
> 
> > We can also ignore all this and say it only works on Windows.
> 
> I think this is a good idea. It may be best to limit support to Windows for purposes of review, as I don't think the supported platform(s) affect review outcome. So I'll shift over to Windows and retry setup. Please just indicate in the setup instructions that only Windows is explicitly supported at this stage.

agreed, the readme has been updated to state clearly that only windows is currently supported.
